# Generated by Django 5.1.5 on 2025-02-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="post_content",
        ),
    ]
